backend:
  name: github
  repo: grycode/affakalite.com.tr
media_folder: static/assets/images/uploads
public_folder: /assets/images/uploads
locale: "tr"
collections:
  - name: blog
    label: Blog
    folder: content/blog
    slug: "{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Featured Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
  - name: page
    label: Sayfalar
    folder: content/pages
    slug: "{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Featured Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
